# =================================================================================================
#     Input Data
# =================================================================================================

# Set the input data, using absolute file paths (relative paths do not work well with some
# of the snakemake tools we are using in the pipeline, such as shadow directories).
data:

  # Input table that lists all samples with their units and fastq files.
  # Paths in the table need to be absolute! No relative paths (e.g., `../data`)!
  samples: "phillips_samples.tsv"

  reference:

    # Name of the reference genome. This has to be a valid snpeff database genome name.
    name: ""

    # Path to the reference genome, using the file ideally as it is provided by the GATK bundle.
    # Path needs to be absolute! No relative path (e.g., `../ref`)!
    genome: "/global/scratch/projects/fc_moilab/projects/aspen/genome/mex_genome/genome.1MX.fasta.gz"

    # Path to any database of known variants (in vcf or vcf.gz format),
    # ideally as it is provided by the GATK bundle.
    # If no such file is available, use an empty list or string instead.
    # Path needs to be absolute! No relative path (e.g., `../var`)!
    known-variants: ""

# =================================================================================================
#    Snakemake settings
# =================================================================================================

max-jobs-per-second: 1
max-status-checks-per-second: 10
#local-cores: 1
latency-wait: 120

# Additional settings used for our purposes
use-conda: True
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True


# =================================================================================================
#     Default Resources
# =================================================================================================
default-resources:
  slurm_partition: "savio3_htc" 
  slurm_account:  "fc_mel"
  runtime: 2880
  cores: 1
  cpus_per_task: 1

# =================================================================================================
#     Tool Parameters
# =================================================================================================

set-resources:

  # ----------------------------------------------------------------------
  #     fastp
  # ----------------------------------------------------------------------
  fastqc:
     threads: 4
        
  # ----------------------------------------------------------------------
  #     fastp
  # ----------------------------------------------------------------------

  # Used only if settings:trimming-tool == fastp
  fastp:
    threads: 2

  # ----------------------------------------------------------------------
  #     trimmomatic
  # ----------------------------------------------------------------------

  # Used only if settings:trimming-tool == trimmomatic
  trimmomatic:
    threads: 2

  # ----------------------------------------------------------------------
  #     bwa-mem2
  # ----------------------------------------------------------------------

  bwa_prep:
    threads: 9
    mem_mb: 80000

  # ----------------------------------------------------------------------
  #     bwa_map
  # ----------------------------------------------------------------------

  # Just under three days to map
  bwa_map:
    mem_mb: 16000
    threads: 2
    runtime: 4319

  # ----------------------------------------------------------------------
  #     samtools_sort
  # ----------------------------------------------------------------------

  samtools_sort:
    mem_mb: 16000
    threads: 2
    runtime: 360

  # ----------------------------------------------------------------------
  #     mark_dups
  # ----------------------------------------------------------------------

  mark_dups:
    mem_mb: 16000
    threads: 2
    runtime: 360

  # ----------------------------------------------------------------------
  #     bamqc
  # ----------------------------------------------------------------------

  bampqc:
    mem_mb: 24000
    threads: 3
    runtime: 1440

  # ----------------------------------------------------------------------
  #     bcftools
  # ----------------------------------------------------------------------

  # Used only if settings:calling-tool == bcftools
  bcftools:
    mpileup: "--max-depth 10000"
    call: ""
    threads: 6
    # concat: ""

  # ----------------------------------------------------------------------
  #     freebayes
  # ----------------------------------------------------------------------

  # Used only if settings:calling-tool == freebayes
  freebayes:
    extra: ""
    chunksize: 100000
    threads: 4
    compress-threads: 2

  # ----------------------------------------------------------------------
  #     gatk
  # ----------------------------------------------------------------------

  gatk:
    # Used only if settings:recalibrate-base-qualities == true
    BaseRecalibrator: ""

    # Used only if settings:calling-tool == haplotypecaller
    HaplotypeCaller: ""
    HaplotypeCaller-threads: 2
    GenotypeGVCFs: ""

    # Used only if settings:vqsr == true
    VariantRecalibrator: ""

  # ----------------------------------------------------------------------
  #     gatk / variantfiltration
  # ----------------------------------------------------------------------

  # Used only if settings:vqsr == false
  variantfiltration-hard:
    # Hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"


  # ----------------------------------------------------------------------
  #     qualimap
  # ----------------------------------------------------------------------

  qualimap:
    # Additional parameters for qualimap
    extra: ""
    threads: 2

  # ----------------------------------------------------------------------
  #     snpeff
  # ----------------------------------------------------------------------

  snpeff:
    # Additional parameters for snpeff, see https://pcingola.github.io/SnpEff/se_commandline/
    # Used only if settings:snpeff == true
    extra: "-Xmx4g"

  # ----------------------------------------------------------------------
  #     mapdamage
  # ----------------------------------------------------------------------

  mapdamage:
    # Additional parameters for mapdamage, see http://ginolhac.github.io/mapDamage/
    # Used only if settings:mapdamage == true
    extra: ""

  # ----------------------------------------------------------------------
  #     damageprofiler
  # ----------------------------------------------------------------------

  damageprofiler:
    # Additional parameters for damageprofiler, see https://damageprofiler.readthedocs.io/en/latest/contents/generalUsage.html
    # Used only if settings:damageprofiler == true
    extra: ""

  # ----------------------------------------------------------------------
  #     multiqc
  # ----------------------------------------------------------------------

  multiqc:
    # Additional parameter for multiqc
    extra: ""
