# =================================================================================================
#     Input Data
# =================================================================================================

# Set the input data, using absolute file paths (relative paths do not work well with some
# of the snakemake tools we are using in the pipeline, such as shadow directories).
data:

  # Input table that lists all samples with their units and fastq files.
  # Paths in the table need to be absolute! No relative paths (e.g., `../data`)!
  samples: "phillips_samples.tsv"

  reference:

    # Name of the reference genome. This has to be a valid snpeff database genome name.
    name: ""

    # Path to the reference genome, using the file ideally as it is provided by the GATK bundle.
    # Path needs to be absolute! No relative path (e.g., `../ref`)!
    genome: "/global/scratch/projects/fc_moilab/projects/aspen/genome/CAM1604/Populus_tremuloides_var_CAM1604-4_HAP1_V2_release/Populus_tremuloides_var_CAM1604-4/sequences/Populus_tremuloides_var_CAM1604-4_HAP1.mainGenome.fasta"

    # Path to any database of known variants (in vcf or vcf.gz format),
    # ideally as it is provided by the GATK bundle.
    # If no such file is available, use an empty list or string instead.
    # Path needs to be absolute! No relative path (e.g., `../var`)!
    known-variants: ""

# =================================================================================================
#    Snakemake settings
# =================================================================================================

max-jobs-per-second: 1
max-status-checks-per-second: 10
#local-cores: 1
latency-wait: 120

# Additional settings used for our purposes
use-conda: True
jobs: 100
max-jobs-per-timespan: "60/1m"
keep-going: True
rerun-incomplete: True
printshellcmds: True


# =================================================================================================
#     Default Resources
# =================================================================================================
default-resources:
  slurm_partition: "savio3_htc" 
  slurm_account:  "ac_moilab"
  runtime: 60
  cores: 1
  cpus_per_task: 1
  mem_mb: 9600

# =================================================================================================
#     Tool Parameters
# =================================================================================================

set-resources:

  # ----------------------------------------------------------------------
  #     fastp
  # ----------------------------------------------------------------------

  # Used only if settings:trimming-tool == fastp
  fastp_trim:
    threads: 1
    mem_mb: 9600
    runtime: 5

  # ----------------------------------------------------------------------
  #     bwa-mem2
  # ----------------------------------------------------------------------

  bwa_prep:
    threads: 9
    mem_mb: 80000

  # ----------------------------------------------------------------------
  #     bwa_map
  # ----------------------------------------------------------------------

  # Just under three days to map
  bwa_map:
    mem_mb: 9600
    threads: 1
    runtime: 60

  # ----------------------------------------------------------------------
  #     samtools_sort
  # ----------------------------------------------------------------------

  samtools_sort:
    mem_mb: 9600
    threads: 1
    runtime: 60

  # ----------------------------------------------------------------------
  #     add_rg
  # ----------------------------------------------------------------------

  add_rg:
    mem_mb: 9600
    threads: 1
    runtime: 60
 
  # ----------------------------------------------------------------------
  #     bamqc
  # ----------------------------------------------------------------------

  bamqc:
    mem_mb: 19200
    threads: 2
    runtime: 60

  # ----------------------------------------------------------------------
  #     bcftools
  # ----------------------------------------------------------------------

  mpileup:
    threads: 2
    mem_mb: 19200
    runtime: 120

  # ----------------------------------------------------------------------
  #     combine_vcfs
  # ----------------------------------------------------------------------

  combine_vcfs:
    threads: 1
    mem_mb: 9600
    runtime: 120

  # ----------------------------------------------------------------------
  #     mapdamage
  # ----------------------------------------------------------------------

  mapdamage:
    # Additional parameters for mapdamage, see http://ginolhac.github.io/mapDamage/
    # Used only if settings:mapdamage == true
    extra: ""

  # ----------------------------------------------------------------------
  #     ANGSD ibs
  # ----------------------------------------------------------------------

  ibs:
    threads: 6
    mem_mb: 57600
    runtime: 2880

  # ----------------------------------------------------------------------
  #     updog_dips
  # ----------------------------------------------------------------------

  updog_dips:
    cpus_per_task: 4
    mem_mb: 38400
    runtime: 2880

  # ----------------------------------------------------------------------
  #     updog_trips
  # ----------------------------------------------------------------------

  updog_trips:
    cpus_per_task: 8
    mem_mb: 76800
    runtime: 4320


  # ----------------------------------------------------------------------
  #     nQuack
  # ---------------------------------------------------------------------- 

  prepare:
   runtime: 300

  process:
   runtime: 300
   cpus_per_task: 10

  infer:
   runtime: 4320
   cpus_per_task: 10

  bootstrap:
   runtime: 4320
   cpus_per_task: 10
