configfile: "profiles/config.yaml"
import pandas as pd
from random import randint

sample_file = pd.read_csv("sequences_to_work_with.11132024.csv", header = 0)
SAMPLE = list(sample_file.filenames)[0:3]
print(SAMPLE)

# =================================================================================================
#     Target Rules
# =================================================================================================
rule all:
    input:
        #fastqc = expand("/global/scratch/users/arphillips/spectral_aspen/qc/fastqc/{sample}_fastqc.zip", sample = SAMPLE),
        #fastp = expand("/global/scratch/users/arphillips/spectral_aspen/data/trimmed/{sample}.trim.fastq.gz" , sample = SAMPLE),
        bamqc = expand("/global/scratch/users/arphillips/spectral_aspen/reports/bamqc/{sample}_stats/qualimapReport.html", sample = SAMPLE)

# =================================================================================================
#     Rule Modules
# =================================================================================================
include: "rules/mapping.smk"
